cmake_minimum_required(VERSION 3.22.1)
include("${CMAKE_CURRENT_LIST_DIR}/../ResolveTdlib.cmake")

if(NOT DEFINED TEST_ROOT OR TEST_ROOT STREQUAL "")
  message(FATAL_ERROR "Pass -DTEST_ROOT=<temporary test output directory>")
endif()
set(expected_commit "42e6a5259551178d1dab54a22ad96d14bd906e20")
set(old_commit "d1085f9cebc5a62379991ae1652673954f229c1f")
set(ndk_revision "27.3.13750724")
set(abi "arm64-v8a")

if(DEFINED FAILURE_CASE)
  set(fixture "${TEST_ROOT}/${FAILURE_CASE}")
  resolve_tdlib_library("${fixture}" "${ndk_revision}" "${abi}" unexpected)
  message(FATAL_ERROR "Expected resolver to reject ${FAILURE_CASE}")
endif()

function(make_fixture name java_commit standard_commit nested_commit)
  set(fixture "${TEST_ROOT}/${name}")
  file(MAKE_DIRECTORY "${fixture}/src/main/java/org/drinkless/tdlib")
  file(WRITE "${fixture}/version.txt" "${expected_commit}\n")
  file(WRITE "${fixture}/src/main/java/org/drinkless/tdlib/TdApi.java"
    "    private static final String GIT_COMMIT_HASH = \"${java_commit}\";\n")
  # Non-printable delimiters model standalone strings in a binary file.
  string(ASCII 1 separator)
  foreach(layout IN ITEMS standard nested)
    if(layout STREQUAL "standard")
      set(directory "${fixture}/src/main/libs/${ndk_revision}/${abi}")
      set(commit "${standard_commit}")
    else()
      set(directory "${fixture}/src/main/libs/${ndk_revision}/libs/${abi}")
      set(commit "${nested_commit}")
    endif()
    if(NOT commit STREQUAL "")
      file(MAKE_DIRECTORY "${directory}")
      file(WRITE "${directory}/libtdjni.so" "binary${separator}${commit}${separator}suffix")
    endif()
  endforeach()
endfunction()

function(expect_library name relative_library)
  resolve_tdlib_library("${TEST_ROOT}/${name}" "${ndk_revision}" "${abi}" actual)
  set(expected "${TEST_ROOT}/${name}/src/main/libs/${ndk_revision}/${relative_library}/libtdjni.so")
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "${name}: expected ${expected}, got ${actual}")
  endif()
endfunction()

function(expect_failure name expected_error)
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DTEST_ROOT=${TEST_ROOT}"
    "-DFAILURE_CASE=${name}" -P "${CMAKE_CURRENT_LIST_FILE}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(result EQUAL 0 OR NOT "${error}" MATCHES "${expected_error}")
    message(FATAL_ERROR "${name}: unexpected result ${result}: ${output}${error}")
  endif()
endfunction()

make_fixture(standard "${expected_commit}" "${expected_commit}" "")
expect_library(standard "${abi}")
make_fixture(nested "${expected_commit}" "${old_commit}" "${expected_commit}")
expect_library(nested "libs/${abi}")
make_fixture(nested_only "${expected_commit}" "" "${expected_commit}")
expect_library(nested_only "libs/${abi}")
make_fixture(prefer_standard "${expected_commit}" "${expected_commit}" "${expected_commit}")
expect_library(prefer_standard "${abi}")
make_fixture(stale "${expected_commit}" "${old_commit}" "${old_commit}")
expect_failure(stale "No compatible libtdjni.so")
make_fixture(missing "${expected_commit}" "" "")
expect_failure(missing "No compatible libtdjni.so")
make_fixture(java_mismatch "${old_commit}" "${expected_commit}" "${expected_commit}")
expect_failure(java_mismatch "TdApi.java does not match")
make_fixture(hash_prefix "${expected_commit}" "${expected_commit}extra" "")
expect_failure(hash_prefix "No compatible libtdjni.so")
make_fixture(invalid_version "${expected_commit}" "${expected_commit}" "")
file(WRITE "${TEST_ROOT}/invalid_version/version.txt" "not-a-commit\n")
expect_failure(invalid_version "Invalid TDLib commit")
message(STATUS "All 9 TDLib prebuilt selection tests passed")
